### ISSUE TITLE
8.6.10版本显示安装成功后并不能看到简体中文选项

### ISSUE THREAD

**Issue by zz447845146** [VOICeVIO/CeVIO.CN#9]
看了一下好像挺久没维护了，是不是已经停止更新了

**Comment by UlyssesWu** [comment]
平日打工忙，没时间关注每个新版本。会修复的，请稍候。

**Comment by UlyssesWu** [comment]
已更新，请尝试最新的 8.6.10.0 release。

**Comment by hujhjh9** [comment]
> 已更新，请尝试最新的 8.6.10.0 release。

感谢 正常使用
